version: '2'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.2
    ports:
    - "1883:1883"
    - "9001:9001"
  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres