---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/JeffreyThijs/quarkus-blog-post.git
    app.quarkus.io/build-timestamp: 2021-03-25 - 13:15:00 +0000
    app.quarkus.io/commit-id: 1554b2ea7b1124e35b18a3cea6a97965bc618bc2
  labels:
    app.kubernetes.io/name: quarkus-blog-post
    app.kubernetes.io/part-of: quarkus-blog-post
    app.kubernetes.io/version: "1.0"
  name: quarkus-blog-post
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-blog-post
    app.kubernetes.io/part-of: quarkus-blog-post
    app.kubernetes.io/version: "1.0"
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/JeffreyThijs/quarkus-blog-post.git
    app.quarkus.io/build-timestamp: 2021-03-25 - 13:15:00 +0000
    app.quarkus.io/commit-id: 1554b2ea7b1124e35b18a3cea6a97965bc618bc2
  labels:
    app.kubernetes.io/name: quarkus-blog-post
    app.kubernetes.io/part-of: quarkus-blog-post
    app.kubernetes.io/version: "1.0"
  name: quarkus-blog-post
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-blog-post
      app.kubernetes.io/part-of: quarkus-blog-post
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/JeffreyThijs/quarkus-blog-post.git
        app.quarkus.io/build-timestamp: 2021-03-25 - 13:15:00 +0000
        app.quarkus.io/commit-id: 1554b2ea7b1124e35b18a3cea6a97965bc618bc2
      labels:
        app.kubernetes.io/name: quarkus-blog-post
        app.kubernetes.io/part-of: quarkus-blog-post
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quarkus-blog-post:1.0
        imagePullPolicy: IfNotPresent
        name: quarkus-blog-post
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
