name: Publish Docker image
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITGUB_PAT }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ github.ref }}
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest

